"""Generate ``docs/js/maps_polygon.js`` from ``shadowinfo/polygon/data`` (the 14 original maps and every path).

The JS demo cannot read files when opened from ``file://``, so the polygons of the original Java
implementation (``data/{1..14}.dat``, y-up and counter-clockwise, never flipped) and ``data/paths.json``
(the code paths of the ``ProjectPanel*`` classes, the paths digitised from the paper figures and the
default demo path of every map, each with its provenance) are embedded in a classic script that sets
``SI.polygonMaps = {provenance, frame, panels, polygons, paths, demo}`` (DESIGN §6).  Every number is
written with Python's shortest round-trip repr, so JS parses the same doubles as
:func:`shadowinfo.polygon.io.load_polygon`.  ``tests/test_polygon_js.py`` checks that the file is up to date.

Usage: ``python tools/gen_js_polygon_maps.py``.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from shadowinfo.polygon.io import DATA_DIR, N_POLYGONS, read_dat  # noqa: E402

OUT = ROOT / "docs" / "js" / "maps_polygon.js"

HEADER = """/* Generated by tools/gen_js_polygon_maps.py from shadowinfo/polygon/data/{1..14}.dat and paths.json -- do not edit.
 * The 14 maps of the original Java implementation (https://github.com/arc-l/shadow-information-space,
 * BSD-3-Clause, Rutgers ARC group), y-up and counter-clockwise ([0, 1000]^2, never flipped), and every
 * robot path: the ProjectPanel* code paths, the paths digitised from the paper figures and the default
 * demo path of each map, with provenance (docs/notes/original_maps.md). */
(function (SI) {
  "use strict";
  SI.polygonMaps = {
"""

FOOTER = """  };
})((globalThis.SI = globalThis.SI || {}));

if (typeof module !== "undefined" && module.exports) module.exports = globalThis.SI;
"""


def _js(x) -> str:
    return json.dumps(x, separators=(", ", ": "), ensure_ascii=False, allow_nan=False)


def _section(name: str, entries: dict) -> str:
    lines = [f"    {name}: {{\n"]
    for k, v in entries.items():
        lines.append(f"      {_js(k)}: {_js(v)},\n")
    lines.append("    },\n")
    return "".join(lines)


def render() -> str:
    data = json.loads((DATA_DIR / "paths.json").read_text())
    polygons = {}
    for n in range(1, N_POLYGONS + 1):
        rec = dict(data["polygons"][str(n)])
        rec["vertices"] = [list(v) for v in read_dat(DATA_DIR / f"{n}.dat")]
        assert len(rec["vertices"]) == rec["n_vertices"]
        polygons[str(n)] = rec
    out = [HEADER]
    out.append(f"    doc: {_js(data['_doc'])},\n")
    out.append(f"    frame: {_js(data['frame'])},\n")
    out.append(f"    provenance: {_js(data['provenance'])},\n")
    out.append(f"    panels: {_js(data['panels'])},\n")
    out.append(_section("polygons", polygons))
    out.append(_section("paths", data["paths"]))
    out.append(_section("demo", data["demo"]))
    out.append(FOOTER)
    return "".join(out)


def main() -> None:
    OUT.write_text(render())
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
