"""Generate ``docs/js/map_<name>.js`` from ``<name>.txt`` and ``<name>_path.json`` in ``shadowinfo/grid/maps/``.

The JS demo cannot read files when opened from ``file://``, so the fixed map
and robot waypoints are embedded in a classic script that registers
``SI.maps[<name>] = {text, waypoints, loop}`` (DESIGN §6).

Usage: ``python tools/gen_js_map.py [name ...]`` (default: ``office``).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MAPS = ROOT / "shadowinfo" / "grid" / "maps"

TEMPLATE = """/* Generated by tools/gen_js_map.py from shadowinfo/grid/maps/{name}.txt and {name}_path.json -- do not edit. */
(function (SI) {{
  "use strict";
  SI.maps = SI.maps || {{}};
  SI.maps[{name_js}] = {{
    text: {text},
    waypoints: {waypoints},
    loop: {loop},
    description: {description},
  }};
}})((globalThis.SI = globalThis.SI || {{}}));

if (typeof module !== "undefined" && module.exports) module.exports = globalThis.SI;
"""


def render(name: str) -> str:
    text = (MAPS / f"{name}.txt").read_text()
    spec = json.loads((MAPS / f"{name}_path.json").read_text())
    lines = text.splitlines()
    text_js = "[\n" + "".join(f"      {json.dumps(l)},\n" for l in lines) + '    ].join("\\n") + "\\n"'
    return TEMPLATE.format(
        name=name,
        name_js=json.dumps(name),
        text=text_js,
        waypoints=json.dumps(spec["waypoints"]),
        loop="true" if spec.get("loop", True) else "false",
        description=json.dumps(spec.get("description", "")),
    )


def main(names: list) -> None:
    for name in names or ["office"]:
        out = ROOT / "docs" / "js" / f"map_{name}.js"
        out.write_text(render(name))
        print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main(sys.argv[1:])
